### PR TITLE
Expose identifier class directly in the CreateOrderAsync method

### PR DESCRIPTION
**Pull request by Maximebb**
As a means of supporting other types of identifiers for acme orders (e.g. https://tools.ietf.org/html/draft-ietf-acme-ip-05), the method for creating an order was overloaded to exposes an `IEnumerable` of `Identifiers`. The original method signature was kept and uses the generic version. This will allow a caller to chose it's identifier type and still keep the old dns-only behavior.

### CODE REVIEW

**Comment by Maximebb** [comment]
I didn't see any particular unit tests where changes were necessary (or needed to be added). Let me know if I missed something.

**Comment by Maximebb** [comment]
#46

**Comment by Maximebb** [comment]
The build not passing doesn't seem related to my changes, is it?

**Comment by ebekker** [comment]
Looks good, thank you for the contribution!

Sorry it took so long -- the CI build was broken and I decided to move it to GitHub Workflows which took a little time to get right.

**Pull request merged**
